"""The only route from this system to a model.

Every generation, audit, summary, interview, judgement, embedding, and token count
passes through a typed protocol declared here, with a versioned prompt, a strict
output schema, a bounded retry policy, and a metadata record. Nothing else in the
repository is permitted to call a provider.

The package is an adapter: it may import ``boto3`` and Strands, which the domain and
policy packages may not. It imports the domain, and never the policies -- a gateway
that knew which mechanism it was serving could come to serve it.
"""

from attention_sink.model_gateway.adapters import (
    RawResponse,
    StrandsInvoker,
    StructuredCaller,
    StructuredCitationAuditor,
    StructuredClaimEvaluator,
    StructuredInterviewer,
    StructuredInvoker,
    StructuredMemorySummarizer,
    StructuredThoughtWriter,
)
from attention_sink.model_gateway.embeddings import (
    SUPPORTED_DIMENSIONS,
    BedrockEmbeddingProvider,
)
from attention_sink.model_gateway.factory import ModelGateway, build_gateway
from attention_sink.model_gateway.failures import (
    RETRYABLE_CODES,
    ModelInvocationError,
    Retrier,
    RetriesExhausted,
    RetryPolicy,
    SchemaRepairNeeded,
    classify,
    is_retryable,
)
from attention_sink.model_gateway.fixtures import (
    FIXTURE_MODEL_ID,
    FIXTURE_REGION,
    SIMULATED_PREFIX,
    FixtureEmbeddingProvider,
    FixtureInvoker,
    FixtureTokenCounter,
    FixtureUnavailableError,
)
from attention_sink.model_gateway.interfaces import (
    DEFAULT_ACCEPTED_LEVELS,
    AuditedCitationRecord,
    AuditResult,
    CitationAuditor,
    ClaimEvaluator,
    EmbeddingProvider,
    EmbeddingResult,
    EvaluationJudgment,
    ExactTokenCounter,
    Interviewer,
    InterviewResult,
    MemorySummarizer,
    SummaryResult,
    ThoughtWriter,
    TokenCount,
    WriterResult,
)
from attention_sink.model_gateway.observability import (
    CallMetadata,
    CallOutcome,
    ModelErrorCode,
    ModelRole,
    request_id_of,
)
from attention_sink.model_gateway.prompts import (
    DEFAULT_PROMPT_VERSION,
    PROMPT_ROOT,
    PromptFormatError,
    PromptLibrary,
    PromptName,
    PromptNotFoundError,
    PromptTemplate,
)
from attention_sink.model_gateway.rendering import (
    MemoryPresentation,
    ModelRequest,
    PromptLeakError,
    UnknownMemoryReferenceError,
    assert_policy_blind,
    build_auditor_request,
    build_evaluation_request,
    build_interview_request,
    build_summarizer_request,
    build_writer_request,
    present_memories,
)
from attention_sink.model_gateway.schemas import (
    EVALUATION_CALCULATION_VERSION,
    EVALUATION_LABELS,
    AuditedCitation,
    AuditOutput,
    ClaimedCitation,
    EmbeddingRecord,
    EvaluationOutput,
    EvaluationTask,
    InterviewAnswer,
    InterviewOutput,
    InterviewQuestion,
    SummaryOutput,
    SupportLevel,
    ThoughtOutput,
    UnsupportedClaim,
    UnsupportedReason,
)
from attention_sink.model_gateway.settings import (
    ConfigurationError,
    GatewaySettings,
    ModelConfig,
    ModelMode,
    RuntimeMode,
    RuntimeSettings,
    WriterInference,
)
from attention_sink.model_gateway.tokens import BEDROCK_COUNTER_VERSION, BedrockTokenCounter

__all__ = [
    "BEDROCK_COUNTER_VERSION",
    "DEFAULT_ACCEPTED_LEVELS",
    "DEFAULT_PROMPT_VERSION",
    "EVALUATION_CALCULATION_VERSION",
    "EVALUATION_LABELS",
    "FIXTURE_MODEL_ID",
    "FIXTURE_REGION",
    "PROMPT_ROOT",
    "RETRYABLE_CODES",
    "RETRYABLE_CODES",
    "SIMULATED_PREFIX",
    "SUPPORTED_DIMENSIONS",
    "AuditOutput",
    "AuditResult",
    "AuditedCitation",
    "AuditedCitationRecord",
    "BedrockEmbeddingProvider",
    "BedrockTokenCounter",
    "CallMetadata",
    "CallOutcome",
    "CitationAuditor",
    "ClaimEvaluator",
    "ClaimedCitation",
    "ConfigurationError",
    "EmbeddingProvider",
    "EmbeddingRecord",
    "EmbeddingResult",
    "EvaluationJudgment",
    "EvaluationOutput",
    "EvaluationTask",
    "ExactTokenCounter",
    "FixtureEmbeddingProvider",
    "FixtureInvoker",
    "FixtureTokenCounter",
    "FixtureUnavailableError",
    "GatewaySettings",
    "InterviewAnswer",
    "InterviewOutput",
    "InterviewQuestion",
    "InterviewResult",
    "Interviewer",
    "MemoryPresentation",
    "MemorySummarizer",
    "ModelConfig",
    "ModelErrorCode",
    "ModelGateway",
    "ModelInvocationError",
    "ModelMode",
    "ModelRequest",
    "ModelRole",
    "PromptFormatError",
    "PromptLeakError",
    "PromptLibrary",
    "PromptName",
    "PromptNotFoundError",
    "PromptTemplate",
    "RawResponse",
    "Retrier",
    "RetriesExhausted",
    "RetryPolicy",
    "RuntimeMode",
    "RuntimeSettings",
    "SchemaRepairNeeded",
    "StrandsInvoker",
    "StructuredCaller",
    "StructuredCitationAuditor",
    "StructuredClaimEvaluator",
    "StructuredInterviewer",
    "StructuredInvoker",
    "StructuredMemorySummarizer",
    "StructuredThoughtWriter",
    "SummaryOutput",
    "SummaryResult",
    "SupportLevel",
    "ThoughtOutput",
    "ThoughtWriter",
    "TokenCount",
    "UnknownMemoryReferenceError",
    "UnsupportedClaim",
    "UnsupportedReason",
    "WriterInference",
    "WriterResult",
    "assert_policy_blind",
    "build_auditor_request",
    "build_evaluation_request",
    "build_gateway",
    "build_interview_request",
    "build_summarizer_request",
    "build_writer_request",
    "classify",
    "is_retryable",
    "present_memories",
    "request_id_of",
]
