"""The paste-ready Builder Center article, derived from the repository version.

Builder Center takes text in one box and images one at a time. So the article that
gets pasted is not the article that renders in this repository: relative image paths
have to become numbered upload markers, and relative links have to become absolute
URLs or they will 404 the moment they leave the repo.

Deriving one file from the other means the two can never say different things. Edit
`AWS_BUILDER_CENTER_ARTICLE.md`; this script rewrites the other one and the upload
table in the publication checklist.

    uv run python scripts/build_paste_ready_article.py
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SHOWCASE = ROOT / "docs" / "showcase"
SOURCE = SHOWCASE / "AWS_BUILDER_CENTER_ARTICLE.md"
TARGET = SHOWCASE / "AWS_BUILDER_CENTER_ARTICLE_PASTE_READY.md"
METADATA = SHOWCASE / "assets" / "source" / "screenshot-metadata.json"

REPO = "https://github.com/varad-more/attention-sink"
BLOB = f"{REPO}/blob/main"

# An SVG renders in a README and cannot be uploaded to Builder Center. Each one has a
# rasterised twin, and the marker has to name the file a person can actually upload.
UPLOADABLE = {
    "assets/readme/cycle-sequence.svg": "article-03-cycle-flow.png",
    "assets/readme/08-architecture.svg": "article-04-architecture.png",
    "assets/charts/origin-recall.svg": "article-07-results-chart.png",
    "assets/charts/prediction-scorecard.svg": "article-08-prediction-scorecard.png",
}

IMAGE = re.compile(r"!\[([^\]]*)\]\(([^)]+)\)\n\n_([^\n]+(?:\n[^\n_][^\n]*)*)_\n")
LINK = re.compile(r"\[([^\]]+)\]\((?!https?://)([^)]+)\)")
REPO_NOTE = re.compile(r"^> \*\*Repository version\.\*\*.*?\n\n", re.S | re.M)

PURPOSE = {
    1: "Opens the article on a real memory death, with the record that proves it.",
    2: "Shows the six minds presented on identical terms.",
    3: "Shows one cycle working end to end.",
    4: "Shows the deployed AWS architecture.",
    5: "Shows the strongest Graveyard Echo, with its caveat.",
    6: "Shows the same question answered by all six minds at the last checkpoint.",
    7: "Shows the headline quantitative result.",
    8: "Shows the preregistered predictions graded, including the failures.",
    9: "Shows the live product working on a phone.",
}


def main() -> int:
    """Rewrite the article for pasting, and refresh the checklist's upload table."""
    article = SOURCE.read_text()
    meta = {a["filename"]: a for a in json.loads(METADATA.read_text())["assets"]}

    rows: list[tuple[int, str, str, str]] = []
    counter = 0

    def marker(match: re.Match[str]) -> str:
        nonlocal counter
        counter += 1
        alt, path, caption = match.group(1), match.group(2), match.group(3)
        name = UPLOADABLE.get(path, path.rsplit("/", 1)[-1])
        if name not in meta:
            raise SystemExit(f"{name} is referenced by the article but was never captured")
        caption = " ".join(caption.split())
        folder = "article" if name.startswith("article") else "readme"
        rows.append((counter, name, caption, alt))
        return (
            f"[ARTICLE IMAGE {counter} — Upload {name} here]\n\n"
            f"- File: `docs/showcase/assets/{folder}/{name}`\n"
            f"- Caption: {caption}\n"
            f"- Alt text: {alt}\n"
            f"- Purpose: {PURPOSE[counter]}\n"
        )

    body = REPO_NOTE.sub("", article)
    body = IMAGE.sub(marker, body)
    if counter != 9:
        raise SystemExit(f"expected nine article images, found {counter}")
    body = LINK.sub(lambda m: f"[{m.group(1)}]({BLOB}/docs/showcase/{m.group(2)})", body)

    header = (
        "<!--\n"
        "  PASTE-READY. Generated by scripts/build_paste_ready_article.py from\n"
        "  AWS_BUILDER_CENTER_ARTICLE.md. Do not edit this file; edit that one.\n\n"
        "  Everything below the rule is the article. The nine [ARTICLE IMAGE n] blocks\n"
        "  are upload instructions, not text to paste: replace each block with the\n"
        "  uploaded image and set the caption and alt text it names.\n"
        "-->\n\n"
    )
    TARGET.write_text(header + body.replace("\n\n\n", "\n\n"))

    checklist = SHOWCASE / "ARTICLE_PUBLICATION_CHECKLIST.md"
    table = "\n".join(
        f"| {n} | `{name}` | {caption} | {alt} | [ ] |" for n, name, caption, alt in rows
    )
    if checklist.exists():
        text = checklist.read_text()
        start = text.index("<!-- ASSET TABLE -->")
        end = text.index("<!-- /ASSET TABLE -->")
        checklist.write_text(
            text[:start]
            + "<!-- ASSET TABLE -->\n\n"
            + "| Order | Filename | Caption | Alt text | Uploaded |\n"
            + "| --- | --- | --- | --- | --- |\n"
            + table
            + "\n\n"
            + text[end:]
        )
        # The repository lints markdown with prettier, and a generated table with
        # unpadded pipes fails that check. Formatting it here keeps the generator and
        # the linter from disagreeing on every run.
        prettier = shutil.which("npx")
        if prettier is not None:
            subprocess.run(  # noqa: S603 - fixed argument vector, no shell, no user input
                [prettier, "prettier", "--write", str(checklist)],
                cwd=ROOT,
                capture_output=True,
                check=False,
            )
        print(f"updated the asset table in {checklist.relative_to(ROOT)}")

    words = len(re.sub(r"\[ARTICLE IMAGE.*?- Purpose:[^\n]*\n", "", body, flags=re.S).split())
    print(f"wrote {TARGET.relative_to(ROOT)} — {counter} image markers, about {words} words")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
