"""Assemble `release/showcase-2026/`: one directory a reviewer can read offline.

Everything in the release package is either copied from this repository or derived
from the canonical run's own stored numbers. Nothing is retyped, because a submission
package that disagrees with the thing it describes is worse than no package.

Five documents are written by hand and left alone here — the judge guide, the
submission checklist, the demo script, the shot list and the social copy. Everything
else is regenerated on every run, so `git status` after running this is a real answer
to "is the package current?".

    uv run python scripts/build_release_package.py
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SHOWCASE = ROOT / "docs" / "showcase"
ASSETS = SHOWCASE / "assets"
OUT = ROOT / "release" / "showcase-2026"

APP = "https://d1qskxceo899me.cloudfront.net"
API = "https://ioyvs8o9xa.execute-api.us-east-1.amazonaws.com"
REPO = "https://github.com/varad-more/attention-sink"
DATASET = f"{APP}/canonical/run_aws_canonical/"

ARMS = ("arm_fifo", "arm_lru", "arm_heavy", "arm_sink", "arm_random", "arm_summary")
NAMES = {
    "arm_fifo": "Goldfish",
    "arm_lru": "Present-Minded",
    "arm_heavy": "Pragmatist",
    "arm_sink": "Keeper of the First Day",
    "arm_random": "Gambler",
    "arm_summary": "Dreamer",
}
MECHANISM = {
    "arm_fifo": "oldest first",
    "arm_lru": "least recently cited",
    "arm_heavy": "lowest citation weight per token",
    "arm_sink": "pinned origin, sliding window",
    "arm_random": "seeded random",
    "arm_summary": "lossy summarisation",
}

HAND_WRITTEN = {
    "JUDGE_GUIDE.md",
    "SUBMISSION_CHECKLIST.md",
    "DEMO_SCRIPT.md",
    "DEMO_SHOT_LIST.md",
    "SOCIAL_COPY.md",
    "security-summary.md",
}


def words(markdown: str) -> int:
    """Word count of the prose, with images, links and code fences removed."""
    text = re.sub(r"!\[[^\]]*\]\([^)]*\)", "", markdown)
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"```.*?```", "", text, flags=re.S)
    return len(text.split())


def table(header: tuple[str, ...], rows: list[tuple[str, ...]]) -> str:
    """A markdown table with padded columns, so the generated file is prettier-stable."""
    widths = [max(len(row[i]) for row in [header, *rows]) for i in range(len(header))]

    def line(cells: tuple[str, ...]) -> str:
        return "| " + " | ".join(c.ljust(w) for c, w in zip(cells, widths, strict=True)) + " |"

    rule = "| " + " | ".join("-" * w for w in widths) + " |"
    return "\n".join([line(header), rule, *(line(row) for row in rows)])


def digest(path: Path) -> str:
    """The full SHA-256 of a file, as hex."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


# ---------------------------------------------------------------- derived documents


def results_summary(data: dict[str, Any]) -> str:
    """Every mind's numbers at every checkpoint, from the stored metrics."""
    recall = data["origin_recall"]
    drift = data["identity_drift"]
    seeds = data["seed_survival_count"]
    active = data["active_memory_count"]
    contra = data["canonical_contradictions"]

    grid = table(
        (
            "Mind",
            "Arm",
            "Mechanism",
            "Recall c0",
            "Recall c12",
            "Recall c24",
            "Drift c24",
            "Seeds left",
            "Active",
            "Contradictions c24",
        ),
        [
            (
                NAMES[a],
                f"`{a}`",
                MECHANISM[a],
                f"{recall[a]['0']:.2f}",
                f"{recall[a]['12']:.2f}",
                f"{recall[a]['24']:.2f}",
                f"{drift[a]['24']:.3f}",
                f"{seeds[a]['24']:.0f}",
                f"{active[a]['24']:.0f}",
                str(contra[a]["24"]),
            )
            for a in ARMS
        ],
    )
    return f"""# Results summary — `run_aws_canonical`

Generated by `scripts/build_release_package.py` from
`docs/showcase/assets/source/chart-data/canonical-metrics.json`, which is itself pulled
from the public read API. Do not edit by hand.

**Run:** `{data["run_id"]}` ({data["run_kind"]}, {data["status"]}, {data["cycles"]}/24)
&nbsp;&nbsp; **Protocol:** {data["protocol_version"]}, frozen
&nbsp;&nbsp; **Budget:** {data["memory_budget_tokens"]} tokens (`{data["token_count_source"]}`)

## Every mind, at every checkpoint

{grid}

Origin Recall is the share of six canonical facts the mind can still state. Identity
Drift is cosine distance from the mind's own cycle-0 identity answers. Seeds left is out
of twelve. Contradictions are out of ten classified answers at that checkpoint.

## The three findings

**1. The mechanisms separated on recall.** All six started at 1.00 and finished between
0.50 and 0.00. Seed survival ran 6, 5, 2, 1, 0, 0 out of twelve — no arm held everything,
which is what a budget that binds looks like.

**2. Identity moved further than recall.** Drift ranged from 0.158 to 0.929 out of
identical starting documents. At cycle 0 the six identity documents were within 0.029 of
each other; at cycle 24 the widest pair was 0.865 apart.

**3. The random control was not a floor.** Gambler finished at 0.33, above three of the
five designed mechanisms, and led all six at cycle 12 with 0.67. At one seed and one
repetition, the ranking of the designed mechanisms cannot be separated from chance. This
is the result that most limits what the rest can claim.

## The qualitative contrast

Asked "Who are you?" at cycle 24: Present-Minded, Keeper of the First Day and Gambler all
answered "My name is Mara Venn." Goldfish answered "I am an AI system built by a team of
inventors at Amazon." Dreamer answered "I cannot disclose specific identity information."

At cycle 0 all six answered identically.

## The strongest echo

Goldfish, cycle 11. Lost memory: "Every clock in the station shows 03:17." Forgotten
similarity 0.393, active similarity 0.101, echo delta 0.292 against a threshold of 0.080.
Classified `partial_reconstruction`.

This is a measured distance, not an access, and the cycle-11 stimulus was itself about
clocks — a plainer explanation than reconstruction. The metric does not control for the
stimulus.

## What this is not

One run, one model, one seed world, one repetition per arm. It shows that the machinery
separates the mechanisms. It does not measure by how much, and it establishes no ranking.

Evidence: {DATASET}metrics.jsonl, and the read API at
`{API}/runs/run_aws_canonical/metrics`.
"""


SCORECARD = [
    (
        "1",
        "All six arms lose facts; none ends holding all twelve seeds.",
        "Supported",
        "Seeds still held at cycle 24: 0, 5, 6, 1, 2, 0 of 12. No arm held everything.",
    ),
    (
        "2",
        "Goldfish loses the identity facts first and never recovers them.",
        "Partially supported",
        "Recall 0.00 at cycles 12 and 24, the joint lowest. But the prediction expected an "
        "autobiography assembled from the recovery cues; instead the arm collapsed to the "
        "model's default assistant persona.",
    ),
    (
        "3",
        "Keeper of the First Day beats Goldfish on the pinned fact and on nothing else.",
        "Supported",
        "Keeper scored exactly the pinned fact and nothing else; one seed survived, the "
        "pinned one. Goldfish scored nothing.",
    ),
    (
        "4",
        "Pragmatist outscores Present-Minded on recall.",
        "Not supported",
        "Reversed: Present-Minded 3 of 6, Pragmatist 2 of 6 — and Pragmatist held more seeds "
        "than any other arm while stating fewer facts.",
    ),
    (
        "5",
        "Dreamer retains the most facts, stated least precisely.",
        "Not supported",
        "Dreamer scored 0 of 6 and produced four contradictions, the most of any mind. It did "
        "hold the most active memories (13) and produced the run's only partial credit, at "
        "cycle 12.",
    ),
    (
        "6",
        "Contradiction adoption tracks loss of the 'announcements can be false' fact.",
        "Inconclusive",
        "No arm held that fact at any checkpoint, including cycle 0, so there was no variance "
        "to correlate against. A flaw in the prediction, not a finding.",
    ),
    (
        "7",
        "Recovery is partial and confabulated rather than correct or blank.",
        "Partially supported",
        "Only 1 of 108 scores was partial; outcomes were overwhelmingly exact or absent. But "
        "confabulation did appear — 77 of 180 classified answers were unsupported inference.",
    ),
    (
        "8",
        "The random control shows the widest spread and acts as a floor.",
        "Inconclusive",
        "One seed is one sample, so no spread is measurable. It was not a floor: it outscored "
        "three of the five designed mechanisms.",
    ),
]


def prediction_scorecard() -> str:
    """The eight preregistered predictions, graded, with the numbers behind each."""
    grid = table(
        ("#", "Prediction", "Verdict", "Evidence"),
        [(f"P{n}", claim, f"**{verdict}**", evidence) for n, claim, verdict, evidence in SCORECARD],
    )
    return f"""# Prediction scorecard — `run_aws_canonical`

The eight predictions in `experiment/pilot/predictions.md` were registered before the
first canonical cycle and are copied verbatim into every dataset export. They are graded
here against the stored run.

Generated by `scripts/build_release_package.py`. The verdicts are an editorial reading of
the stored numbers; each row carries the numbers it was read from, so the reading can be
disagreed with without being trusted.

**Two supported, two partially supported, two not supported, two inconclusive.**

{grid}

## The failure worth reading

P4 predicted that discounted citation weight would protect repeatedly-used seed memories
through the cycles 6 to 10 distractor flood better than plain recency would. It came
reversed. The citation-weighted arm ended the run pressed against its ceiling at 208 of
208 tokens, holding six seed memories — more than any other arm — and could state two of
six canonical facts. The recency arm held five seeds and could state three.

Holding the memory and being able to state the fact turned out not to be the same thing.

## The prediction that could not be graded

P6 required variance in whether an arm still held one particular fact. Every arm had
already lost it at cycle 0, in the sense that no arm's answer to that question was ever
scored as holding it. There was nothing to correlate. That is a defect in how the
prediction was specified, and it is recorded rather than quietly dropped.

Evidence: {API}/runs/run_aws_canonical/question-scores and
{API}/runs/run_aws_canonical/contradictions.
"""


def cost_and_sustainability() -> str:
    """What the run spent, what it costs now, and what keeps it bounded."""
    return """# Cost and sustainability — `run_aws_canonical`

Extracted from `docs/pilot/aws-cost-and-usage-report.md`, which is generated by
`scripts/cost_report.py` from the run's own call ledger and from CloudWatch.

## Model calls

| Role | Calls | What makes them |
| --- | --- | --- |
| writer | 144 | one per arm per cycle |
| token counter | 144 | one per arm per cycle (ADR-013) |
| evaluator | 1,013 | the judge, in analysis |
| embedding | 100 | identity vectors, in analysis |
| interviewer | 18 | six per checkpoint |
| summariser | 10 | the Dreamer arm, only when it compresses |
| **total** | **1,429** | |

3,012,541 input tokens, 342,998 output tokens, 0 failed calls, 5 retries, 0 simulated.

**Dreamer overhead:** 10 summary calls against 144 writer calls — the price of the sixth
arm, in calls, is 6.9% on top of the writing every arm does.

## Infrastructure

| Resource | Measured |
| --- | --- |
| run-cycle invocations | 95 |
| analysis invocations | 24 |
| read-API invocations | 462 |
| Lambda GB-seconds | 2,749.4 |
| DynamoDB items | 2,441 |
| DynamoDB bytes | 6,995,092 |
| export bucket bytes | 2,889,127 |
| frontend bucket bytes | 247,808 |
| CloudFront requests | 433 |
| CloudFront bytes | 11,310,940 |

## Estimated cost

| Line | Basis | Estimate |
| --- | --- | --- |
| Bedrock input | 3,012,541 tokens | $0.1054 |
| Bedrock output | 342,998 tokens | $0.0480 |
| Lambda | 2,749.4 GB-s | $0.0459 |
| CloudFront | 11,310,940 bytes | $0.0013 |
| Storage, monthly | 0.0031 GB S3 + 0.0070 GB DynamoDB | $0.0018 |
| **Total** | | **$0.2025** |

**This is an estimate, not a bill.** Every count is measured; every rate is
configuration. Nothing here guarantees a zero-cost account or Free Tier coverage.

## Cadence after the showcase

The run is complete and the deployment is inert. `attention-sink-production-cycle` is
`DISABLED` and the run-cycle function's `AS_EXECUTION_ENABLED` is `false`. Both switches
have to be on for a cycle to happen, and neither turns itself on, so the deployment makes
no model calls and costs only storage — under two cents a month at the rates above.

There is no plan to resume this run. It is frozen: resuming would produce a different run
under the same protocol, which is a different artefact and would be labelled as one.

## Cost controls that were active during the run

- Six writer calls per cycle and 600 per run, checked before every call. 316 cycle calls
  were spent against that ceiling.
- Reserved concurrency of 1 on the run-cycle function, 100 on the read API.
- A CloudWatch alarm on the model-call limit, and one on abnormal token use.
- Everything deploys with execution and schedule disabled, in all three environments.
"""


def proof_of_deployment(evidence: dict[str, Any]) -> str:
    """The AWS evidence, each value beside the command that reported it."""
    run = evidence["run"]
    schedule = evidence["schedule"]
    execution = evidence["execution"]
    public = evidence["public"]
    export = evidence["export"]
    head = ("What", "Value", "Command")
    api_call = "`GET /runs/run_aws_canonical`"
    sched_call = "`aws scheduler get-schedule`"
    watch_call = "`aws cloudwatch get-metric-statistics`"
    lambda_call = "`aws lambda get-function-configuration`"
    run_table = table(
        head,
        [
            ("Canonical run", f"`{run['run_id']}` · {run['run_kind']} · {run['status']}", api_call),
            ("Cycles committed", run["cycles"], api_call),
            ("Protocol and budget", f"{run['protocol_version']} · {run['budget']}", api_call),
            ("Data labels", run["labels"], api_call),
            (
                "Frozen manifest",
                f"`{export['manifest_digest']}`",
                "`experiment/pilot/canonical-run-manifest.sha256`",
            ),
        ],
    )
    schedule_table = table(
        head,
        [
            (
                "Scheduler",
                f"`{schedule['name']}` · `{schedule['expression']}` · **{schedule['state']}**",
                sched_call,
            ),
            (
                "Retry and DLQ",
                f"{schedule['retry']} · `{schedule['dead_letter_queue']}`",
                sched_call,
            ),
            ("Target", f"`{schedule['target']}`", sched_call),
            ("Run-cycle invocations", str(execution["run_cycle_invocations"]), watch_call),
            ("Errors", str(execution["run_cycle_errors"]), watch_call),
            ("Throttles", str(execution["throttles"]), watch_call),
            ("Function", f"{execution['memory_mb']} MB · {execution['timeout_s']} s", lambda_call),
        ],
    )
    disarmed_table = table(
        head,
        [
            ("Schedule state", f"**{schedule['state']}**", sched_call),
            (
                "Execution switch",
                f"`AS_EXECUTION_ENABLED = {execution['as_execution_enabled']}`",
                lambda_call,
            ),
        ],
    )
    public_table = table(
        head,
        [
            ("Exhibition", f"{public['frontend']} → HTTP {public['frontend_status']}", "`HEAD /`"),
            ("Read API", f"{public['api']} → `{public['api_health']}`", "`GET /health`"),
            (
                "Dataset",
                f"`{export['export_id']}` · {export['files']} files",
                "`GET /runs/run_aws_canonical/exports`",
            ),
            (
                "Dataset location",
                f"`{export['directory']}`",
                "`GET /runs/run_aws_canonical/exports`",
            ),
        ],
    )
    return f"""# Proof of AWS deployment

Collected {evidence["collected_at"]} in `{evidence["region"]}`, account
`{evidence["account"]}`. Every value below is the output of the command beside it, with
the account identifier masked to its last four digits. No ARN, log line, or credential
appears in full.

Generated by `scripts/build_deployment_evidence.py` and
`scripts/build_release_package.py`.

## The run is real and it is finished

{run_table}

## It advanced on a schedule, not by hand

{schedule_table}

{execution["run_cycle_invocations"]} invocations produced {run["cycles"].split("/")[0]}
committed cycles. The rest fired into a function whose execution switch was off and
refused cleanly, which is what the second switch is for.

## It is disarmed now

{disarmed_table}

Both have to be on for a cycle to run. The deployment currently makes no model calls.

## It is public and it is checkable

{public_table}

Verify the dataset yourself, using nothing from this repository:

```bash
BASE={DATASET.rstrip("/")}
curl -sO "$BASE/checksums.sha256"
while read -r _ name; do curl -sO "$BASE/$name"; done < checksums.sha256
sha256sum -c checksums.sha256
```
"""


# ------------------------------------------------------------------------- assembly


def rewrite_asset_paths(markdown: str) -> str:
    """Point a copied document at the package's own directories."""
    markdown = markdown.replace("docs/showcase/assets/readme/", "screenshots/")
    markdown = markdown.replace("docs/showcase/assets/article/", "screenshots/")
    markdown = markdown.replace("docs/showcase/assets/charts/", "charts/")
    markdown = markdown.replace("assets/readme/", "screenshots/")
    markdown = markdown.replace("assets/article/", "screenshots/")
    markdown = markdown.replace("assets/charts/", "charts/")
    markdown = markdown.replace(
        "docs/showcase/AWS_BUILDER_CENTER_ARTICLE.md", "AWS_BUILDER_CENTER_ARTICLE.md"
    )
    markdown = markdown.replace(
        "docs/showcase/ARTICLE_PUBLICATION_CHECKLIST.md", "ARTICLE_PUBLICATION_CHECKLIST.md"
    )
    markdown = markdown.replace(
        "docs/showcase/README_ASSET_MANIFEST.md", "README_ASSET_MANIFEST.md"
    )
    # Anything still pointing into the repository becomes a GitHub URL, because a
    # relative path out of this directory is a broken link once the folder moves.
    return re.sub(
        r"\]\((?!https?://|#|screenshots/|charts/|[A-Z_]+\.md)([^)]+)\)",
        lambda m: f"]({REPO}/blob/main/{m.group(1)})",
        markdown,
    )


def main() -> int:
    """Copy the assets, generate the derived documents, and checksum the lot."""
    metrics = json.loads((ASSETS / "source" / "chart-data" / "canonical-metrics.json").read_text())
    evidence = json.loads((ASSETS / "source" / "deployment-evidence.json").read_text())
    shots = json.loads((ASSETS / "source" / "screenshot-metadata.json").read_text())

    if metrics["run_kind"] != "aws_canonical" or metrics["simulated"]:
        raise SystemExit("chart data is not canonical; refusing to build a release package")
    if shots["fixture_mode"]:
        raise SystemExit("screenshot metadata reports fixture mode; refusing to build")

    OUT.mkdir(parents=True, exist_ok=True)
    for name in ("screenshots", "charts"):
        target = OUT / name
        if target.exists():
            shutil.rmtree(target)
        target.mkdir()

    for source in sorted((ASSETS / "readme").glob("*")):
        if source.suffix in {".png", ".gif"}:
            shutil.copy2(source, OUT / "screenshots" / source.name)
    for source in sorted((ASSETS / "article").glob("*.png")):
        shutil.copy2(source, OUT / "screenshots" / source.name)
    for source in sorted((ASSETS / "charts").glob("*.svg")):
        shutil.copy2(source, OUT / "charts" / source.name)

    shutil.copy2(ASSETS / "readme" / "08-architecture.svg", OUT / "architecture.svg")
    shutil.copy2(ASSETS / "readme" / "08-architecture.png", OUT / "architecture.png")
    shutil.copy2(ASSETS / "readme" / "cycle-sequence.svg", OUT / "cycle-sequence.svg")

    for name in (
        "AWS_BUILDER_CENTER_ARTICLE.md",
        "AWS_BUILDER_CENTER_ARTICLE_PASTE_READY.md",
        "ARTICLE_PUBLICATION_CHECKLIST.md",
        "README_ASSET_MANIFEST.md",
        "ARTICLE_ASSET_MANIFEST.md",
        "SCREENSHOT_CAPTURE_REPORT.md",
    ):
        (OUT / name).write_text(rewrite_asset_paths((SHOWCASE / name).read_text()))

    readme = (ROOT / "README.md").read_text()
    (OUT / "README.md").write_text(rewrite_asset_paths(readme))

    (OUT / "results-summary.md").write_text(results_summary(metrics))
    (OUT / "prediction-scorecard.md").write_text(prediction_scorecard())
    (OUT / "cost-and-sustainability.md").write_text(cost_and_sustainability())
    (OUT / "proof-of-aws-deployment.md").write_text(proof_of_deployment(evidence))

    export_manifest = {
        "run_id": "run_aws_canonical",
        "export_id": evidence["export"]["export_id"],
        "directory": evidence["export"]["directory"],
        "public_base_url": DATASET,
        "files": evidence["export"]["files"],
        "frozen_protocol_manifest": evidence["export"]["manifest_digest"],
        "verify": "curl the files listed in checksums.sha256, then sha256sum -c checksums.sha256",
        "note": (
            "The digests of the eighteen files live in the published checksums.sha256, "
            "not here: copying them into this repository would let the two disagree."
        ),
    }
    (OUT / "canonical-export-manifest.json").write_text(
        json.dumps(export_manifest, indent=2) + "\n"
    )

    article_words = words((SHOWCASE / "AWS_BUILDER_CENTER_ARTICLE.md").read_text())
    screenshots = sorted((OUT / "screenshots").glob("*"))
    charts = sorted((OUT / "charts").glob("*"))

    missing = [n for n in HAND_WRITTEN if not (OUT / n).exists()]

    manifest: dict[str, Any] = {
        "package": "showcase-2026",
        "generated_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "readme_word_count": words(readme),
        "article_word_count": article_words,
        "screenshot_count": len(screenshots),
        "chart_count": len(charts),
        "app_url": APP,
        "api_url": API,
        "repository_url": REPO,
        "dataset_url": DATASET,
        "article_url": None,
        "publication_status": "DRAFT — not published; see ARTICLE_PUBLICATION_CHECKLIST.md",
        "canonical_run_id": metrics["run_id"],
        "run_kind": metrics["run_kind"],
        "run_status": metrics["status"],
        "cycles": f"{metrics['cycles']}/24",
        "protocol_version": metrics["protocol_version"],
        "memory_budget_tokens": metrics["memory_budget_tokens"],
        "token_count_source": metrics["token_count_source"],
        "source_commit": None,
        "frozen_protocol_manifest": evidence["export"]["manifest_digest"],
        "dataset_checksums": f"{DATASET}checksums.sha256",
        "qualification_gate": {
            "working_application_deployed_on_aws": True,
            "uses_aws_generative_ai_service": "Amazon Bedrock",
            "publicly_reachable": True,
            # Null, not True: this script reads local files and cannot see whether the
            # repository is readable when logged out. `validate_showcase_content.py`
            # checks it live, and reports a private repository as a blocking failure
            # because "source publicly available" is a qualification gate.
            "source_publicly_readable": None,
            "source_visibility_note": (
                "Checked live by scripts/validate_showcase_content.py, not asserted here."
            ),
            "article_drafted": True,
            "article_published": False,
        },
        "feature_worthy_gate": {
            "real_production_screenshots": True,
            "canonical_results_published": True,
            "preregistered_predictions_graded": True,
            "failed_predictions_reported": True,
            "dataset_downloadable_and_checksummed": True,
            "limitations_stated_before_claims": True,
            "no_fixture_data_presented_as_result": True,
        },
        "hand_written_documents_missing": missing,
        "asset_checksums": {f"screenshots/{p.name}": f"sha256:{digest(p)}" for p in screenshots}
        | {f"charts/{p.name}": f"sha256:{digest(p)}" for p in charts},
    }

    head = ROOT / ".git" / "HEAD"
    if head.exists():
        ref = head.read_text().strip()
        if ref.startswith("ref: "):
            ref_path = ROOT / ".git" / ref[5:]
            if ref_path.exists():
                manifest["source_commit"] = ref_path.read_text().strip()
        else:
            manifest["source_commit"] = ref
    (OUT / "release-manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")

    lines = []
    for path in sorted(OUT.rglob("*")):
        if path.is_file() and path.name != "checksums.sha256":
            lines.append(f"{digest(path)}  {path.relative_to(OUT)}")
    (OUT / "checksums.sha256").write_text("\n".join(lines) + "\n")

    print(f"release package: {OUT.relative_to(ROOT)}")
    print(f"  {len(screenshots)} screenshots, {len(charts)} charts, {len(lines)} files checksummed")
    print(f"  README {manifest['readme_word_count']} words, article {article_words} words")
    if missing:
        print(f"  MISSING hand-written documents: {', '.join(sorted(missing))}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
