"""The two diagrams the README and the article carry.

Hand-laid out rather than generated by a diagramming tool, for one reason: both have
to stay readable at GitHub's README width and inside a blog column, and every layout
engine that was tried put a label on top of an edge at that size. The graph these draw
is the one recorded in `architecture.mmd` and `cycle-sequence.mmd`; those files are the
source of truth for what connects to what, and this script is the source of truth for
where it sits on the page. Change the graph in the `.mmd` first, then here.

Nothing here reads the run. These are pictures of the deployment, not of a result.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "showcase" / "assets" / "readme"

FONT = "ui-sans-serif, -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif"
PAPER = "#fbfaf8"
INK = "#1d1a17"
MUTED = "#6b645c"
CARD = "#ffffff"

WRITE = "#a5701f"
STORE = "#4a5a72"
ANALYSE = "#3f7a52"
READ = "#2f6b8f"
EXPORT = "#8a5a9c"
OPS = "#6b645c"


def esc(text: str) -> str:
    """Escape the three characters that would break SVG text."""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def text(
    x: float,
    y: float,
    body: str,
    *,
    size: float = 12,
    fill: str = INK,
    anchor: str = "start",
    weight: str = "400",
    style: str = "normal",
) -> str:
    """One SVG text node, positioned and styled."""
    return (
        f'<text x="{x:.1f}" y="{y:.1f}" font-family="{FONT}" font-size="{size}" '
        f'font-weight="{weight}" font-style="{style}" fill="{fill}" '
        f'text-anchor="{anchor}">{esc(body)}</text>'
    )


def box(
    x: float,
    y: float,
    w: float,
    h: float,
    lines: list[str],
    *,
    colour: str,
    dashed: bool = False,
) -> str:
    """One labelled box: a card with a coloured header rule and up to four lines."""
    stroke = ' stroke-dasharray="5 4"' if dashed else ""
    parts = [
        f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="7" fill="{CARD}" '
        f'stroke="{colour}" stroke-width="1.6"{stroke}/>',
        f'<rect x="{x}" y="{y}" width="{w}" height="4" rx="2" fill="{colour}"/>',
    ]
    top = y + 26
    for i, line in enumerate(lines):
        parts.append(
            text(
                x + w / 2,
                top + i * 16,
                line,
                size=12.5 if i == 0 else 11,
                fill=INK if i == 0 else MUTED,
                anchor="middle",
                weight="600" if i == 0 else "400",
            )
        )
    return "".join(parts)


def arrow(points: list[tuple[float, float]], *, colour: str, dashed: bool = False) -> str:
    """A polyline edge with an arrowhead in its own colour."""
    path = " ".join(f"{x:.1f},{y:.1f}" for x, y in points)
    dash = ' stroke-dasharray="6 5"' if dashed else ""
    return (
        f'<polyline points="{path}" fill="none" stroke="{colour}" stroke-width="1.8" '
        f'stroke-linejoin="round" marker-end="url(#tip-{colour.lstrip("#")})"{dash}/>'
    )


def markers() -> str:
    """The six arrowhead markers, one per path colour."""
    out = []
    for colour in (WRITE, STORE, ANALYSE, READ, EXPORT, OPS):
        out.append(
            f'<marker id="tip-{colour.lstrip("#")}" viewBox="0 0 10 10" refX="9" refY="5" '
            f'markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
            f'<path d="M 0 0 L 10 5 L 0 10 z" fill="{colour}"/></marker>'
        )
    return "<defs>" + "".join(out) + "</defs>"


def frame(width: int, height: int, title: str, subtitle: str, body: str, label: str) -> str:
    """The outer SVG, its title, its subtitle and its accessible label."""
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" '
        f'width="{width}" height="{height}" role="img" aria-label="{esc(label)}">'
        + markers()
        + f'<rect width="{width}" height="{height}" fill="{PAPER}"/>'
        + text(40, 44, title, size=19, weight="600")
        + text(40, 67, subtitle, size=12.5, fill=MUTED)
        + body
        + "</svg>"
    )


# ------------------------------------------------------------------ architecture


def architecture() -> str:
    """The deployed AWS architecture, laid out by hand for legibility."""
    w, h = 1240, 986
    p: list[str] = []

    def band(x: float, y: float, body: str, colour: str) -> None:
        p.append(text(x, y, body, size=12.5, fill=colour, weight="600"))

    # Row A — scheduled generation. 226-wide boxes leave a 48px gap for edge labels.
    band(48, 104, "1 · SCHEDULED GENERATION", WRITE)
    p.append(
        box(
            48,
            130,
            226,
            92,
            [
                "EventBridge Scheduler",
                "attention-sink-production-cycle",
                "rate(2 minutes) · retry 2 · UTC",
                "state: DISABLED",
            ],
            colour=WRITE,
        )
    )
    p.append(
        box(
            322,
            130,
            226,
            92,
            [
                "Lambda — Run-Cycle",
                "python3.12 · 1024 MB · 600 s",
                "reserved concurrency 1",
                "refuses unless armed",
            ],
            colour=WRITE,
        )
    )
    p.append(
        box(
            596,
            130,
            226,
            92,
            [
                "Amazon Bedrock",
                "amazon.nova-micro-v1:0",
                "writer · summariser",
                "token counter (ADR-013)",
            ],
            colour=WRITE,
        )
    )
    p.append(
        box(
            870,
            130,
            226,
            92,
            [
                "Amazon SQS",
                "scheduler dead-letter queue",
                "a fire that never ran",
                "is not silently lost",
            ],
            colour=OPS,
            dashed=True,
        )
    )

    p.append(arrow([(274, 176), (316, 176)], colour=WRITE))
    p.append(text(295, 168, "invoke", size=10.5, fill=WRITE, anchor="middle"))
    p.append(arrow([(548, 176), (590, 176)], colour=WRITE))
    p.append(text(569, 168, "12 calls", size=10.5, fill=WRITE, anchor="middle"))
    p.append(arrow([(161, 130), (161, 120), (983, 120), (983, 126)], colour=OPS, dashed=True))
    p.append(text(700, 114, "undelivered fire", size=10.5, fill=OPS, anchor="middle"))

    # Row B — the spine. Everything above writes it; everything below reads it.
    band(846, 262, "2 · PERSISTENCE", STORE)
    p.append(
        box(
            322,
            264,
            510,
            84,
            [
                "Amazon DynamoDB — one table",
                "run · arm states · 144 cycle snapshots · 157 graveyard records",
                "2,062 metric rows · 18 interviews · model-call ledger",
                "deletion protection on; snapshots written under attribute_not_exists",
            ],
            colour=STORE,
        )
    )
    p.append(arrow([(375, 222), (375, 258)], colour=STORE))
    p.append(
        text(387, 250, "TransactWriteItems — six arms commit or none do", size=10.5, fill=STORE)
    )

    # Row C — analysis, off the write path.
    band(48, 392, "3 · ASYNCHRONOUS ANALYSIS", ANALYSE)
    p.append(
        box(
            48,
            410,
            226,
            92,
            [
                "Amazon EventBridge",
                "cycle-completed event",
                "one rule, one target",
                "",
            ],
            colour=ANALYSE,
        )
    )
    p.append(
        box(
            322,
            410,
            226,
            92,
            [
                "Lambda — Analysis",
                "python3.12 · 1536 MB · 900 s",
                "recall, drift, echo,",
                "contradiction",
            ],
            colour=ANALYSE,
        )
    )
    p.append(
        box(
            596,
            410,
            226,
            92,
            [
                "Amazon Bedrock",
                "nova-micro judge",
                "titan-embed-text-v2",
                "1,113 analysis calls",
            ],
            colour=ANALYSE,
        )
    )
    p.append(
        box(
            870,
            410,
            226,
            92,
            [
                "Amazon SQS",
                "analysis dead-letter queue",
                "analysis can fail without",
                "corrupting a result",
            ],
            colour=OPS,
            dashed=True,
        )
    )

    p.append(arrow([(435, 222), (435, 240), (161, 240), (161, 404)], colour=ANALYSE))
    p.append(text(300, 233, "emit cycle-completed", size=10.5, fill=ANALYSE, anchor="middle"))
    p.append(arrow([(274, 456), (316, 456)], colour=ANALYSE))
    p.append(arrow([(548, 456), (590, 456)], colour=ANALYSE))
    p.append(arrow([(520, 410), (520, 354)], colour=ANALYSE))
    p.append(text(532, 380, "metrics, echoes, contradictions", size=10.5, fill=ANALYSE))
    p.append(arrow([(435, 502), (435, 518), (983, 518), (983, 506)], colour=OPS, dashed=True))

    # Row D and E — the public read path.
    band(48, 560, "4 · PUBLIC READ PATH", READ)
    p.append(
        box(
            48,
            578,
            200,
            84,
            [
                "Visitor's browser",
                "no account, no cookie,",
                "no analytics",
                "",
            ],
            colour=READ,
        )
    )
    p.append(
        box(
            286,
            578,
            236,
            84,
            [
                "Amazon CloudFront",
                "Origin Access Control",
                "CSP, HSTS, nosniff,",
                "frame DENY, no-referrer",
            ],
            colour=READ,
        )
    )
    p.append(
        box(
            560,
            578,
            236,
            84,
            [
                "Amazon S3 — frontend",
                "private bucket",
                "direct object GET → 403",
                "",
            ],
            colour=READ,
        )
    )
    p.append(
        box(
            286,
            698,
            236,
            84,
            [
                "Amazon API Gateway",
                "HTTP API · GET only",
                "CORS pinned to the",
                "distribution, never *",
            ],
            colour=READ,
        )
    )
    p.append(
        box(
            560,
            698,
            236,
            84,
            [
                "Lambda — Read API",
                "python3.12 · 512 MB · 29 s",
                "reserved concurrency 100",
                "IAM holds no write action",
            ],
            colour=READ,
        )
    )

    p.append(arrow([(248, 620), (280, 620)], colour=READ))
    p.append(arrow([(522, 620), (554, 620)], colour=READ))
    p.append(text(538, 612, "/", size=10.5, fill=READ, anchor="middle"))
    p.append(arrow([(404, 662), (404, 692)], colour=READ))
    p.append(text(416, 682, "/api/*", size=10.5, fill=READ))
    p.append(arrow([(522, 740), (554, 740)], colour=READ))
    p.append(arrow([(796, 740), (1150, 740), (1150, 306), (838, 306)], colour=READ))
    p.append(text(1140, 296, "read-only", size=10.5, fill=READ, anchor="end"))

    # Row F — the export, routed down the left margin so it crosses nothing.
    band(48, 816, "5 · DATASET EXPORT", EXPORT)
    p.append(
        box(
            330,
            834,
            236,
            84,
            [
                "Export command",
                "18 files + checksums.sha256",
                "manifest carries the",
                "protocol digest",
            ],
            colour=EXPORT,
        )
    )
    p.append(
        box(
            604,
            834,
            236,
            84,
            [
                "Amazon S3 — export",
                "private bucket",
                "canonical/ prefix is the",
                "only prefix CloudFront serves",
            ],
            colour=EXPORT,
        )
    )
    p.append(
        box(
            878,
            834,
            262,
            84,
            [
                "6 · Cross-cutting",
                "CloudWatch logs, 4 alarms, metrics",
                "IAM least-privilege per function",
                "13-field log allowlist; no raw text",
            ],
            colour=OPS,
            dashed=True,
        )
    )

    p.append(arrow([(322, 320), (30, 320), (30, 876), (324, 876)], colour=EXPORT))
    p.append(arrow([(566, 876), (598, 876)], colour=EXPORT))
    p.append(arrow([(840, 876), (862, 876), (862, 548), (404, 548), (404, 572)], colour=EXPORT))
    p.append(
        text(
            636,
            540,
            "the dataset is served from the same distribution as the exhibition",
            size=10.5,
            fill=EXPORT,
            anchor="middle",
        )
    )

    p.append(
        text(
            48,
            950,
            "One bounded cycle at a time. Analysis is never on the path that writes the "
            "experiment, and the read route table registers no write verb.",
            size=11,
            fill=MUTED,
            style="italic",
        )
    )
    p.append(
        text(
            48,
            968,
            "Every bucket is private. Nothing is public except CloudFront. "
            "Everything deploys inert: execution off, schedule off.",
            size=11,
            fill=MUTED,
            style="italic",
        )
    )

    return frame(
        w,
        h,
        "Attention Sink on AWS",
        "us-east-1 · account ****2684 · one CDK application, three environments, "
        "all deployed with execution disabled",
        "".join(p),
        "Deployed AWS architecture: EventBridge Scheduler invokes a Run-Cycle Lambda that "
        "calls Bedrock and commits six arms atomically to DynamoDB, emits a cycle-completed "
        "event to an Analysis Lambda, while CloudFront serves a private S3 frontend and an "
        "API Gateway read path backed by a read-only Lambda, and the dataset export lands in "
        "a private S3 bucket served through the same distribution.",
    )


# ---------------------------------------------------------------- cycle sequence

LANES = [
    ("EventBridge\nScheduler", WRITE),
    ("Run-Cycle\nLambda", WRITE),
    ("Amazon\nBedrock", WRITE),
    ("Policy\nengine", STORE),
    ("Amazon\nDynamoDB", STORE),
    ("Amazon\nEventBridge", ANALYSE),
    ("Analysis\nLambda", ANALYSE),
    ("Public\nread API", READ),
    ("Exhibition\nfrontend", READ),
]

STEPS = [
    (0, 1, "invoke — rate(2 minutes), one cycle", WRITE),
    (1, 4, "load six committed arm states and the next stimulus", STORE),
    (1, 2, "six writer calls: same stimulus, same prompt, no arm name", WRITE),
    (2, 1, "journal entry, candidate memory, claimed citations", WRITE),
    (1, 3, "validate citations against the active set", STORE),
    (3, 2, "Dreamer only: one extra call to write the summary", WRITE),
    (3, 1, "evict or compress until the arm fits 208 tokens", STORE),
    (1, 4, "TransactWriteItems — all six snapshots, or none", STORE),
    (1, 5, "emit cycle-completed", ANALYSE),
    (5, 6, "rule fires", ANALYSE),
    (6, 4, "recall, drift, echo, contradiction — written back", ANALYSE),
    (8, 7, "visitor opens a cycle", READ),
    (7, 4, "read committed state only; a cycle in flight is invisible", READ),
]


def cycle_sequence() -> str:
    """One cycle as a sequence diagram across nine participants."""
    w = 1240
    left = 68
    lane_w = (w - left - 40) / len(LANES)
    head_y = 110
    first = 200
    gap = 40
    h = int(first + len(STEPS) * gap + 90)

    p: list[str] = []
    xs = [left + lane_w * (i + 0.5) for i in range(len(LANES))]
    for i, (label, colour) in enumerate(LANES):
        x = xs[i]
        p.append(
            f'<rect x="{x - lane_w / 2 + 6:.1f}" y="{head_y}" width="{lane_w - 12:.1f}" '
            f'height="46" rx="6" fill="{CARD}" stroke="{colour}" stroke-width="1.4"/>'
        )
        for li, line in enumerate(label.split("\n")):
            p.append(text(x, head_y + 20 + li * 14, line, size=11, anchor="middle", weight="600"))
        p.append(
            f'<line x1="{x:.1f}" y1="{head_y + 46}" x2="{x:.1f}" y2="{h - 62}" '
            f'stroke="#ddd7ce" stroke-width="1.4"/>'
        )

    for i, (a, b, label, colour) in enumerate(STEPS):
        y = first + i * gap
        x1, x2 = xs[a], xs[b]
        direction = 1 if x2 > x1 else -1
        p.append(
            f'<line x1="{x1:.1f}" y1="{y:.1f}" x2="{x2 - direction * 7:.1f}" y2="{y:.1f}" '
            f'stroke="{colour}" stroke-width="1.8" '
            f'marker-end="url(#tip-{colour.lstrip("#")})"/>'
        )
        p.append(text(28, y + 4, f"{i + 1:>2}", size=11, fill=MUTED, weight="600"))
        mid = (x1 + x2) / 2
        p.append(text(mid, y - 9, label, size=11, anchor="middle"))

    p.append(
        text(
            68,
            h - 34,
            "Steps 1 to 8 are the experiment. Everything after step 8 reads what "
            "step 8 committed and can never change it.",
            size=11.5,
            fill=MUTED,
            style="italic",
        )
    )

    return frame(
        w,
        h,
        "One cycle, end to end",
        "The same thirteen steps ran twenty-four times. A cycle that fails part-way "
        "commits nothing and the next fire starts it again.",
        "".join(p),
        "Sequence diagram of one Attention Sink cycle from EventBridge Scheduler through "
        "the Run-Cycle Lambda, Bedrock, the policy engine and DynamoDB, then the "
        "cycle-completed event to the Analysis Lambda, and finally the public read API "
        "serving the exhibition frontend.",
    )


def main() -> int:
    """Write both diagrams."""
    OUT.mkdir(parents=True, exist_ok=True)
    for name, svg in (
        ("08-architecture.svg", architecture()),
        ("cycle-sequence.svg", cycle_sequence()),
    ):
        path = OUT / name
        path.write_text(svg + "\n")
        print(f"wrote {path.relative_to(ROOT)} ({path.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
