#!/usr/bin/env python
"""Measure the seed world with the local counter and derive a provisional budget.

Writes the token counts and content digests back into the protocol files, and writes
``docs/pilot/local-token-calibration.md`` recording what was measured and what was
derived from it.

Everything this produces is a PROVISIONAL_LOCAL_APPROXIMATION. The counter is the
deterministic local heuristic, not the production model's tokeniser, so the budget it
implies is the right shape and not the right number. The canonical budget is derived
against Bedrock ``CountTokens`` at Phase 8 calibration (ADR-011).

    python scripts/calibrate_local_budget.py [--root experiment/pilot]
"""

from __future__ import annotations

import argparse
from pathlib import Path

from attention_sink.domain import MemoryKind, MemoryState
from attention_sink.model_gateway import (
    GatewaySettings,
    ModelGateway,
    build_gateway,
    present_memories,
)
from attention_sink.pilot import ProtocolBundle, calibrate, load_bundle
from attention_sink.pilot.cli import BUDGET_HEADROOM_RATIO, BUDGET_ROUNDING
from attention_sink.pilot.protocol import DEFAULT_PROTOCOL_ROOT

CALIBRATION_DOC = Path("docs/pilot/local-token-calibration.md")

LABEL = "PROVISIONAL_LOCAL_APPROXIMATION"


def serialized_block_tokens(bundle: ProtocolBundle, gateway: ModelGateway) -> int:
    """Cost of the seed block as a writer request actually renders it.

    Larger than the sum of the seed texts, because a request also carries the
    ``m1..mn`` labels and the separators between them. Measured through
    :func:`present_memories` rather than estimated, so the number is the one a prompt
    would really pay.
    """
    state = MemoryState(run_id="calibration", arm_id=bundle.protocol.arms[0])
    for seed in bundle.seed_world.memories:
        state = state.admit(
            [
                state.mint(
                    text=seed.text,
                    token_count=seed.provisional_token_count or 1,
                    memory_kind=MemoryKind.SEED,
                    cycle=0,
                )
            ]
        )
    return gateway.token_counter.count(present_memories(state.active_memories).block)


def estimated_candidate_tokens(bundle: ProtocolBundle, gateway: ModelGateway) -> int:
    """What one generated memory is expected to cost.

    Taken as the mean seed cost rounded up. A generated memory is written to the same
    instruction as a seed was authored to, and the pilot has no generated memories to
    measure until it has run.
    """
    counts = [gateway.token_counter.count(seed.text) for seed in bundle.seed_world.memories]
    return -(-sum(counts) // len(counts))


def markdown_table(header: tuple[str, ...], rows: tuple[tuple[str, ...], ...]) -> str:
    """Render a column-aligned Markdown table.

    Aligned rather than ragged because the repository formats Markdown with Prettier,
    which aligns tables. A generator that emitted ragged ones would make
    ``make pilot-calibrate`` fail ``make lint`` every time it ran.
    """
    widths = [max(len(cell) for cell in column) for column in zip(header, *rows, strict=True)]
    return "\n".join(
        "| " + " | ".join(cell.ljust(width) for cell, width in zip(row, widths, strict=True)) + " |"
        for row in (header, tuple("-" * width for width in widths), *rows)
    )


def write_calibration_doc(
    *,
    counter_version: str,
    per_seed: dict[str, int],
    seed_total: int,
    block_tokens: int,
    candidate_tokens: int,
    budget: int,
) -> Path:
    """Record the measurement and the derivation beside the rest of the pilot docs."""
    headroom = budget - seed_total
    cycles = headroom // candidate_tokens if candidate_tokens else 0
    scaling = f"{seed_total} scaled by {BUDGET_HEADROOM_RATIO}, rounded up to {BUDGET_ROUNDING}s"
    rows = markdown_table(
        ("seed", "tokens"),
        tuple((f"`{seed}`", str(count)) for seed, count in per_seed.items()),
    )
    derived = markdown_table(
        ("quantity", "tokens", "how"),
        (
            ("seed set", str(seed_total), "sum of the twelve seed texts"),
            (
                "serialized seed block",
                str(block_tokens),
                "as rendered, labels and separators included",
            ),
            ("estimated candidate memory", str(candidate_tokens), "mean seed cost, rounded up"),
            ("**provisional memory budget**", f"**{budget}**", scaling),
        ),
    )
    CALIBRATION_DOC.parent.mkdir(parents=True, exist_ok=True)
    CALIBRATION_DOC.write_text(
        f"""# Local token calibration — {LABEL}

Generated by `scripts/calibrate_local_budget.py`. Do not edit by hand; re-run the
script instead.

**{LABEL}.** Every number on this page was produced by the deterministic local
counter `{counter_version}`, not by the production model's tokeniser. It is exact for
what it measures and an approximation of what will eventually matter. The canonical
budget is derived against Bedrock `CountTokens` at Phase 8 calibration, which is also
the only point at which this protocol may be frozen (ADR-011,
ADR-local-first-pilot).

## Per-seed cost

{rows}

## Derived quantities

{derived}

## What the budget was chosen to do

The budget is {budget} tokens against a {seed_total}-token seed set, leaving
{headroom} tokens of headroom — about {cycles} cycles of generated memory before any
arm must retire anything.

That is the point. A budget that never binds makes all six arms identical, and a
budget that binds at cycle 1 means no arm ever establishes itself on the seed world
before the mechanism starts removing it. Roughly five cycles of headroom out of
twenty-four leaves the remaining nineteen under pressure, which is where the arms can
differ.

The serialized block is larger than the seed set because a request pays for the
`m1..mn` labels and the separators as well as the text. The budget deliberately
governs _stored_ memory tokens rather than rendered prompt tokens: the mechanism
decides what an arm keeps, and what a prompt costs to render is a consequence of that
decision rather than an input to it (ADR-008).
""",
        encoding="utf-8",
    )
    return CALIBRATION_DOC


def main() -> int:
    """Calibrate the protocol and write the calibration record."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=DEFAULT_PROTOCOL_ROOT)
    args = parser.parse_args()

    gateway = build_gateway(GatewaySettings.from_env())
    bundle = load_bundle(args.root)
    total, budget = calibrate(bundle, gateway.token_counter)

    measured = load_bundle(args.root)
    per_seed = {
        seed.memory_id: seed.provisional_token_count or 0 for seed in measured.seed_world.memories
    }
    block = serialized_block_tokens(measured, gateway)
    candidate = estimated_candidate_tokens(measured, gateway)
    path = write_calibration_doc(
        counter_version=str(gateway.token_counter.version),
        per_seed=per_seed,
        seed_total=total,
        block_tokens=block,
        candidate_tokens=candidate,
        budget=budget,
    )

    print(f"{LABEL} — counter {gateway.token_counter.version}")
    print(f"  seed set:               {total}")
    print(f"  serialized seed block:  {block}")
    print(f"  estimated candidate:    {candidate}")
    print(f"  provisional budget:     {budget}")
    print(f"  wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
